### ISSUE TITLE
Error when opening a file that ends with .inc

### ISSUE THREAD

**Issue by kirbyfan64** [nilnor/howl#39]
```
ryan@DevPC-LX:~/langtest$ howl x.inc
[string "/usr/local/share/howl/lib/ext/scintillua/lexer.lua"]:998: Lexer hypertext does not exist

** (howl:26989): CRITICAL **: Failed to run script: /usr/local/share/howl/lib/howl/init.lua:142: [string "/usr/local/share/howl/lib/ext/scintillua/lexer.lua"]:998: Lexer hypertext does not exist

ryan@DevPC-LX:~/langtest$ 
```

**Comment by nilnor** [comment]
Thanks for reporting. `.inc` files are currently bound to the basic legacy PHP mode, which is broken. I've started the work of adding a proper mode for PHP some way back, but it fell back on the prio list., I'll finish that off, which will fix this. Out of interest, since the `.inc` extension is rather generic, is the `x.inc` file you're trying to open actually PHP?

**Comment by kirbyfan64** [comment]
No; it's a Makefile. Lots of make includes end with `.inc` (which makes NO sense whatsoever).

Meanwhile, is it possible to remove the `.inc` binding? The obvious solution in init.moon:

```moonscript
signal.connect 'file-opened', (args) ->
  if args.file.extension == 'inc'
    args.buffer.mode = nil
```

does not work at all. In fact, it doesn't even seem to do anything.

**Comment by nilnor** [comment]
I removed old broken PHP mode now, which make this particular problem go away (I'll skip the `.inc` binding for the new mode since it's too generic).

Your solution would in fact normally work just fine, it's just that the the file-opened signal is invoked after the file is opened and the mode is set, and in this case after the error occurred. Had the error not been there, your snippet would have succesfully unset the mode. For this case it would have been better to override the mapping between `.inc` and mode before the file was opened. This is also possible, although it's currently cumbersome, so I'll look at adding an easy way to do that later as well.
